'use strict';

const version = "2026.04.04";
const cacheID = "lumikasa-"+version;
const resources = [
	"./",
	"index.html",
	"lumikasa.js",
	"favicon.svg",
	"favicon.ico",
	"manifest.webmanifest",
	"assets/crosshair1.gif",
	"assets/crosshair2.gif",
	"assets/crosshair3.gif",
	"assets/crosshair4.gif",
	"assets/terrain.gif",
	"assets/cancel.ogg",
	"assets/charge.ogg",
	"assets/confirm.ogg",
	"assets/death.ogg",
	"assets/select.ogg",
	"assets/shot.ogg",
	"assets/snow.ogg",
	"assets/level0.png",
	"assets/level1.png",
	"assets/level2.png",
	"assets/level3.png",
	"assets/level4.png",
	"assets/level5.png",
	"assets/level6.png",
	"assets/level7.png",
	"assets/level8.png",
	"assets/level9.png",
	"assets/level10.png",
	"assets/level11.png",
	"assets/level12.png",
	"assets/level13.png",
	"assets/level14.png",
	"assets/level15.png",
	"assets/level16.png",
	"assets/level17.png",
	"assets/level18.png",
	"assets/level19.png",
	"assets/level20.png",
	"assets/level21.png",
	"assets/level22.png",
	"assets/level23.png",
	"assets/level24.png",
	"assets/level25.png",
	"assets/level26.png",
	"assets/level27.png",
	"assets/level28.png",
	"assets/level29.png",
	"assets/level30.png",
	"assets/level31.png",
	"assets/level32.png",
	"assets/level33.png",
	"assets/level34.png",
	"assets/level35.png",
	"assets/level36.png",
	"assets/level37.png",
	"assets/level38.png",
	"assets/level39.png",
	"assets/level40.png",
	"assets/level41.png",
	"assets/level42.png",
	"assets/level43.png",
	"assets/level44.png",
	"assets/level45.png",
	"assets/level46.png",
	"assets/level47.png",
	"assets/level48.png",
	"assets/level49.png",
	"assets/level50.png",
	"assets/level51.png",
	"assets/level52.png",
	"assets/level53.png",
	"assets/level54.png",
	"assets/level55.png",
	"assets/level56.png",
	"assets/level57.png",
	"assets/level58.png",
	"assets/level59.png",
	"assets/level60.png",
	"assets/level61.png",
	"assets/level62.png",
	"assets/level63.png",
	"assets/level64.png",
	"assets/level65.png",
	"assets/level66.png",
	"assets/level67.png",
	"assets/level68.png",
	"assets/stage0.png",
	"assets/stage1.png",
	"assets/stage2.png",
	"assets/stage3.png",
	"assets/stage4.png",
	"assets/stage5.png",
	"assets/stage6.png",
	"assets/stage7.png"
];

self.addEventListener('install', (e) => {
	e.waitUntil(caches.open(cacheID).then((cache) => cache.addAll(resources)));
});

self.addEventListener('activate', (e) => {
	e.waitUntil(caches.keys().then((cacheIDs) => Promise.all(cacheIDs.map((id) => {
		if(id!==cacheID) return caches.delete(id);
	}))));
});

self.addEventListener('fetch', (e) => {
	e.respondWith(caches.match(e.request).then((response) => response || fetch(e.request)));
});